[package]
name = "clink"
version = "0.7.1"
authors = ["Serhiy Barhamon <bargamon@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.8.2"
linkify = "0.10.0"
url = "2.4.1"
rustop = "1.1.2"
rand = "0.8.5"
confy = "0.5.1"
serde = { version = "1.0.188", features = ["derive", "rc"] }
chrono = "0.4.31"
dirs-next = "2.0.0"
toml = "0.8.0"
