[package]
name = "clink"
version = "0.6.4"
authors = ["Serhiy Barhamon <bargamon@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.8.2"
linkify = "0.9.0"
url = "2.4.0"
rustop = "1.1.2"
rand = "0.8.5"
confy="0.5.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
dirs-next = "2.0.0"
toml = "0.7.4"
